---
Region: us-east-1
Image:
  Os: alinux2
  # CustomAmi: ami-08e31a824b0e1ec59  # alinux2-x86-sbo-pcluster-v5
Monitoring:
  Logs:
    CloudWatch:
      RetentionInDays: 90
      DeletionPolicy: Delete
HeadNode: !include _head_node.tpl.yaml
Scheduling:
  Scheduler: slurm
  SlurmSettings:
    EnableMemoryBasedScheduling: true
    # CustomSlurmSettingsIncludeFile: s3://sboinfrastructureassets/config/slurm_extras.conf
  SlurmQueues: !include _slurm_queues.tpl.yaml
Imds:
  ImdsSupport: v2.0
SharedStorage:
  - Name: Efs-Home
    StorageType: Efs
    MountDir: /sbo/home
    EfsSettings:
      FileSystemId: !config efs_id
